In [1]:
!pip install scikit-learn
!pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

In [3]:
import os
print(os.path.exists("Used_Bikes.csv"))

True


In [4]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\Used_Bikes.csv")


In [5]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [6]:
df.head(10)  ##head uper k 5 element

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
5                          Yamaha FZs 150cc   53499.0      Delhi     25000.0   
6             Honda CB Hornet 160R  ABS DLX   85000.0      Delhi      8200.0   
7       Hero Splendor Plus Self Alloy 100cc   45000.0      Delhi     12645.0   
8         Royal Enfield Thunderbird X 350cc  145000.0  Bangalore      9190.0   
9  Royal Enfield Classic Desert Storm 500cc   88000.0      Delhi     19000.0   

          owner  age  power          brand  
0   First Owner  3.0  110.0            TVS  
1   First Owner  4.0  350.0  Royal Enfield  
2   First Owner  8.0  675.0        Triumph  
3   First Owner  4.0  180.0            TVS  
4   First Owner  3.0  150.0         Yamaha  
5   First Owner  6.0  150.0         Yamaha  
6   First Owner  3.0  160.0          Honda  
7   First Owner  3.0  100.0           Hero  
8   First Owner  3.0  350.0  Royal Enfield  
9  Second Owner  7.0  500.0  Royal Enfield

In [7]:
df.tail()

bike_name    price    city  kms_driven        owner  \
32643     Hero Passion Pro 100cc  39000.0   Delhi     22000.0  First Owner   
32644       TVS Apache RTR 180cc  30000.0  Karnal      6639.0  First Owner   
32645   Bajaj Avenger Street 220  60000.0   Delhi     20373.0  First Owner   
32646  Hero Super Splendor 125cc  15600.0  Jaipur     84186.0  First Owner   
32647         Bajaj Pulsar 150cc  22000.0    Pune     60857.0  First Owner   

        age  power  brand  
32643   4.0  100.0   Hero  
32644   9.0  180.0    TVS  
32645   6.0  220.0  Bajaj  
32646  16.0  125.0   Hero  
32647  13.0  150.0  Bajaj

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [9]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [10]:
df.describe()

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [11]:
df.isnull()

bike_name  price   city  kms_driven  owner    age  power  brand
0          False  False  False       False  False  False  False  False
1          False  False  False       False  False  False  False  False
2          False  False  False       False  False  False  False  False
3          False  False  False       False  False  False  False  False
4          False  False  False       False  False  False  False  False
...          ...    ...    ...         ...    ...    ...    ...    ...
32643      False  False  False       False  False  False  False  False
32644      False  False  False       False  False  False  False  False
32645      False  False  False       False  False  False  False  False
32646      False  False  False       False  False  False  False  False
32647      False  False  False       False  False  False  False  False

[32648 rows x 8 columns]

In [12]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [13]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [14]:
df.duplicated().sum()

25324

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

0

In [17]:
##df.dropna()
df

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

            owner  age  power            brand  
0     First Owner  3.0  110.0              TVS  
1     First Owner  4.0  350.0    Royal Enfield  
2     First Owner  8.0  675.0          Triumph  
3     First Owner  4.0  180.0              TVS  
4     First Owner  3.0  150.0           Yamaha  
...           ...  ...    ...              ...  
9362  First Owner  8.0  150.0             Hero  
9369  First Owner  9.0  220.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9371  First Owner  4.0  400.0            Bajaj  
9372  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [18]:
df['bike_name']

0         TVS Star City Plus Dual Tone 110cc
1                Royal Enfield Classic 350cc
2                       Triumph Daytona 675R
3                       TVS Apache RTR 180cc
4       Yamaha FZ S V 2.0 150cc-Ltd. Edition
                        ...                 
9362               Hero Hunk Rear Disc 150cc
9369                     Bajaj Avenger 220cc
9370          Harley-Davidson Street 750 ABS
9371                   Bajaj Dominar 400 ABS
9372                Bajaj Avenger Street 220
Name: bike_name, Length: 7324, dtype: object

In [19]:
df['brand']

0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...       
9362               Hero
9369              Bajaj
9370    Harley-Davidson
9371              Bajaj
9372              Bajaj
Name: brand, Length: 7324, dtype: object

In [20]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [21]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [22]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [23]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [24]:
df

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

            owner  age  power            brand  
0     First Owner  3.0  110.0              TVS  
1     First Owner  4.0  350.0    Royal Enfield  
2     First Owner  8.0  675.0          Triumph  
3     First Owner  4.0  180.0              TVS  
4     First Owner  3.0  150.0           Yamaha  
...           ...  ...    ...              ...  
9362  First Owner  8.0  150.0             Hero  
9369  First Owner  9.0  220.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9371  First Owner  4.0  400.0            Bajaj  
9372  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [25]:
df=df.drop(['city','bike_name'],axis=1)

In [26]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [27]:
cat_col =df.select_dtypes(include='object')

In [28]:
cat_col

owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [29]:

num_cal=df.select_dtypes(exclude='object')

In [30]:
num_cal

price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [31]:
# bike brand = tvs 
# kms = 50000
# price = 50000

tvs_df =df[df['brand']=='TVS']
 

In [32]:
tvs_df[tvs_df['kms_driven']==50000]

price  kms_driven        owner   age  power brand
1224  28000.0     50000.0  First Owner   7.0  180.0   TVS
7147  25700.0     50000.0  First Owner  10.0  160.0   TVS
8842  45000.0     50000.0  First Owner   7.0  180.0   TVS

In [33]:
hero_df = df[
    (df['brand'] == 'Hero') &
    (df['price'] <= 50000) &
    (df['owner'] == 'Second Owner') &
    (df['age'] >= 2)
]
hero_df

price  kms_driven         owner   age  power brand
377   38000.0     17376.0  Second Owner   5.0  100.0  Hero
592   32000.0     21884.0  Second Owner   8.0  100.0  Hero
805   23000.0     25000.0  Second Owner   6.0  125.0  Hero
1046  22100.0     24000.0  Second Owner   7.0  100.0  Hero
1068  34500.0     80000.0  Second Owner  10.0  150.0  Hero
...       ...         ...           ...   ...    ...   ...
8685  16800.0     35000.0  Second Owner  13.0  100.0  Hero
8925  16000.0     26512.0  Second Owner  16.0  100.0  Hero
8929  30000.0     40000.0  Second Owner   5.0  125.0  Hero
9029  14000.0     50000.0  Second Owner  19.0  100.0  Hero
9339  11400.0     20000.0  Second Owner  17.0  100.0  Hero

[78 rows x 6 columns]

In [34]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [35]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [36]:
#machin learning
#maths
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [37]:
owner_dict={'First Owner':1, 'Second Owner':2, 'Third Owner':3,
       'Fourth Owner Or More':4}

In [38]:
owner_dict

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More': 4}

In [39]:
df['owner']=df['owner'].map(owner_dict)

In [40]:
df

price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [41]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [42]:
brand_dict = {
    'TVS':0, 'Royal Enfield':1, 'Triumph':2, 'Yamaha':3, 'Honda':4, 'Hero':5,
       'Bajaj':6, 'Suzuki':7, 'Benelli':8, 'KTM':9, 'Mahindra':10, 'Kawasaki':11,
       'Ducati':12, 'Hyosung':13, 'Harley-Davidson':14, 'Jawa':15, 'BMW':16, 'Indian':17,
       'Rajdoot':18, 'LML':19, 'Yezdi':20, 'MV':21, 'Ideal':22
}

In [43]:
df['brand'] = df['brand'].map(brand_dict)

In [44]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      0
1     119900.0     11000.0      1  4.0  350.0      1
2     600000.0       110.0      1  8.0  675.0      2
3      65000.0     16329.0      1  4.0  180.0      0
4      80000.0     10000.0      1  3.0  150.0      3
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      5
9369   35000.0     60000.0      1  9.0  220.0      6
9370  450000.0      3430.0      1  4.0  750.0     14
9371  139000.0     21300.0      1  4.0  400.0      6
9372   80000.0      7127.0      1  5.0  220.0      6

[7324 rows x 6 columns]

In [45]:
df.corr()

price  kms_driven     owner       age     power     brand
price       1.000000   -0.199951 -0.005188 -0.248752  0.807641  0.288409
kms_driven -0.199951    1.000000  0.062612  0.367518 -0.168295 -0.036161
owner      -0.005188    0.062612  1.000000  0.203151  0.043746  0.005844
age        -0.248752    0.367518  0.203151  1.000000 -0.164211 -0.030263
power       0.807641   -0.168295  0.043746 -0.164211  1.000000  0.068647
brand       0.288409   -0.036161  0.005844 -0.030263  0.068647  1.000000

In [46]:
x=df.drop('price',axis=1)
y=df[['price']]

In [47]:
x ##independent variable

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      0
1        11000.0      1  4.0  350.0      1
2          110.0      1  8.0  675.0      2
3        16329.0      1  4.0  180.0      0
4        10000.0      1  3.0  150.0      3
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      5
9369     60000.0      1  9.0  220.0      6
9370      3430.0      1  4.0  750.0     14
9371     21300.0      1  4.0  400.0      6
9372      7127.0      1  5.0  220.0      6

[7324 rows x 5 columns]

In [48]:
y ###dependent variable

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [49]:
# model training step
# data spliting -----> test or training(testing model testing)(training model the model)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [50]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [51]:
# modeling training step
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [52]:
print("training score:-",model.score(x_train,y_train))

training score:- 0.7201556885169937


In [53]:
print("testing score:-",model.score(x_test,y_test))

testing score:- 0.7207968187531595


In [54]:
pred=model.predict(x_test)

In [55]:
import numpy as np

In [56]:
y_test=np.array(y_test).ravel()

In [57]:
pred = np.ravel(pred)
y_test = np.ravel(y_test)

# Now this will work correctly
history = pd.DataFrame({
    "predicted": pred,
    "actual": y_test
})

print(history)

          predicted     actual
0      17343.663758    25000.0
1      98050.627585    67000.0
2      54785.742828    29000.0
3       3617.685354    18000.0
4      83246.924508    35000.0
...             ...        ...
1460   18750.896605    34500.0
1461  117692.256210   126999.0
1462  644132.134336  1000000.0
1463  130414.985037   110000.0
1464  134340.155369   110000.0

[1465 rows x 2 columns]


In [58]:
import joblib
joblib.dump(model,'linear_regression_model')

['linear_regression_model']

In [59]:
model.predict(x_test)

array([[ 17343.66375811],
       [ 98050.62758542],
       [ 54785.74282763],
       ...,
       [644132.13433631],
       [130414.98503719],
       [134340.15536933]])

In [60]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [61]:
x , y =load_breast_cancer(return_X_y=True)

In [62]:
x # independent coloum 

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [63]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [65]:
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [66]:
logistic_model =LogisticRegression(max_iter=10000, random_state=0)


In [67]:
logistic_model.fit(x_train,y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [68]:
logistic_model.score(x_train,y_train)

0.9626373626373627

In [69]:
pred =logistic_model.predict(x_test)

In [70]:
pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0])

In [71]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0])

In [72]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,SVR

In [73]:
x , y=load_iris(return_X_y=True)

In [74]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [75]:
svm_model =SVC(kernel='rbf', gamma=0.5, C=1.0)  #  high = overfit , low = underfit (0.01), gamma is used to single output , kernal is used to non linear data 

In [76]:
svm_model.fit(x_train,y_train)

SVC(gamma=0.5)

In [77]:
svm_model.score(x_train,y_train)

0.975

In [78]:
svm_model.score(x_test,y_test)

1.0

In [79]:
pred=svm_model.predict(x_test)

In [80]:
pred

array([2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 0, 0, 2, 2, 1, 0,
       0, 1, 2, 0, 0, 2, 0, 2])

In [81]:
y_test

array([2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 0, 0, 2, 2, 1, 0,
       0, 1, 2, 0, 0, 2, 0, 2])

In [82]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

## KNN ALgo

In [83]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [84]:
iris=load_iris()
x=iris.data
y=iris.target

In [85]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [86]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [87]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [88]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [89]:
knn.score(x_train,y_train)

0.9583333333333334

In [90]:
#Linear Regression
# Logistic Regression
#svm_model
#KNN


## performance metrics(model evaluation techniques)

In [91]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import(accuracy_score,
                            precision_score,
                            recall_score,
                            f1_score,
                            classification_report)

In [92]:
x , y =load_iris().data, load_iris().target

In [93]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [94]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [95]:
knn_model=KNeighborsClassifier(n_neighbors=3)

In [96]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [97]:
pred=knn_model.predict(x_test)

In [98]:
pred

array([1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 2, 2, 0])

In [99]:
acc=accuracy_score(y_test,pred)
print("accuracy_score:-",acc)
ps  =precision_score(y_test,pred, average='macro')
print("precision_score:-",ps)
rs=recall_score(y_test,pred,average='macro')
print("recall_score:-",rs)
f1_score=f1_score(y_test,pred,average='macro')
print("f1_score:-",f1_score)


accuracy_score:- 0.9666666666666667
precision_score:- 0.9743589743589745
recall_score:- 0.9583333333333334
f1_score:- 0.9644444444444445


In [100]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor


In [101]:
RFC_obj=RandomForestClassifier(n_estimators=200,
                               criterion='entropy',
                               max_depth=3,
                               min_samples_split=2,
                               min_samples_leaf=2) #hyper parameter

In [102]:
RFC_obj.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 3,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [103]:
RFC_obj.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=3, min_samples_leaf=2,
                       n_estimators=200)

In [104]:
RFC_obj.score(x_train,y_train)

0.9833333333333333

In [105]:
RFC_obj.score(x_test,y_test)

0.9333333333333333

In [106]:
pred=RFC_obj.predict(x_test)

In [107]:
pred

array([1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       0, 0, 2, 0, 1, 2, 2, 0])

In [108]:
y_test

array([1, 1, 2, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 2, 2, 0])

In [109]:
# from sklearn.ensemble import VotingClassifier, StackingClassifier
# Data set >>>>cleaning , preprocess , EDA 
# RandomForestClassifier, RandomForestRegressor
# model Train 
# model save
   
# next flask 

In [110]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
dt=DecisionTreeClassifier()

In [111]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
from sklearn.

In [ ]:
from sklearn.datasets import load_iris
