In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
df =pd.read_csv('Credit.csv')

In [3]:
df

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4521 rows x 9 columns]

In [4]:
from sklearn.datasets import load_iris
x , y= load_iris(return_X_y=True)

In [5]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\Internship 2june\Deep learning\ANN\clean_Credit_RNN.csv')
x=df.drop('approval',axis=1)
y =df['approval']

In [6]:
x

age  job  marital  education   balance  housing  duration  campaign
0     0.149780   10        1          0  0.068455        0  0.000037  0.000000
1     0.156388    7        1          1  0.108750        1  0.000043  0.000000
2     0.160793    4        2          2  0.062590        1  0.000041  0.000000
3     0.149780    4        1          2  0.064281        1  0.000042  0.061224
4     0.213656    1        1          1  0.044469        1  0.000043  0.000000
...        ...  ...      ...        ...       ...      ...       ...       ...
4516  0.301762    7        1          1  0.039999        1  0.000047  0.081633
4517  0.209251    6        1          2  0.000000        1  0.000027  0.000000
4518  0.209251    9        1          1  0.048429        0  0.000040  0.204082
4519  0.145374    1        1          1  0.059731        0  0.000039  0.061224
4520  0.180617    2        2          2  0.059717        1  0.000048  0.020408

[4521 rows x 8 columns]

In [7]:
input_shape = x.shape[1]

In [8]:

input_shape

8

In [9]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2)

In [12]:
model =Sequential()
model.add(Dense(units=128, activation='relu', input_shape=(input_shape,)))  ### input layer

# Dropout layer 
model.add(Dropout(0.2))

### hidden layer 
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))



# output layer 

model.add(Dense(units=1, activation='sigmoid')) 



model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1152      
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 16)                528       
                                                                 
 dense_4 (Dense)             (None, 8)                 136       
                                                                 
 dense_5 (Dense)             (None, 1)                 9

In [14]:
model.fit(x_train , y_train , epochs=10)

Epoch 1/10
113/113 [==============================] - 6s 16ms/step - loss: 0.4382 - accuracy: 0.8670
Epoch 2/10
113/113 [==============================] - 1s 9ms/step - loss: 0.3642 - accuracy: 0.8816
Epoch 3/10
113/113 [==============================] - 1s 8ms/step - loss: 0.3634 - accuracy: 0.8816
Epoch 4/10
113/113 [==============================] - 2s 14ms/step - loss: 0.3633 - accuracy: 0.8816
Epoch 5/10
113/113 [==============================] - 1s 13ms/step - loss: 0.3594 - accuracy: 0.8816
Epoch 6/10
113/113 [==============================] - 1s 12ms/step - loss: 0.3584 - accuracy: 0.8816
Epoch 7/10
113/113 [==============================] - 2s 17ms/step - loss: 0.3571 - accuracy: 0.8816
Epoch 8/10
113/113 [==============================] - 2s 17ms/step - loss: 0.3547 - accuracy: 0.8816
Epoch 9/10
113/113 [==============================] - 1s 8ms/step - loss: 0.3579 - accuracy: 0.8816
Epoch 10/10
113/113 [==============================] - 1s 9ms/step - loss: 0.3565 - accuracy: 

In [15]:
model.predict(  x_test)

29/29 [==============================] - 1s 7ms/step


array([[0.09540414],
       [0.14075191],
       [0.07804977],
       [0.10818487],
       [0.14953291],
       [0.07447375],
       [0.16732429],
       [0.1648043 ],
       [0.08976199],
       [0.12692262],
       [0.11533408],
       [0.08073328],
       [0.17187849],
       [0.16520686],
       [0.06817972],
       [0.03390395],
       [0.14947885],
       [0.15578146],
       [0.18403378],
       [0.10367434],
       [0.15837595],
       [0.16779873],
       [0.08329915],
       [0.06320141],
       [0.14400704],
       [0.15593071],
       [0.06195348],
       [0.14495441],
       [0.21433064],
       [0.09192348],
       [0.0792989 ],
       [0.07023936],
       [0.08188625],
       [0.06132464],
       [0.06873176],
       [0.07867333],
       [0.078596  ],
       [0.08155871],
       [0.16896284],
       [0.13702941],
       [0.12371799],
       [0.16054514],
       [0.17447121],
       [0.15679938],
       [0.17296869],
       [0.17879531],
       [0.19735007],
       [0.146

In [16]:
x

age  job  marital  education   balance  housing  duration  campaign
0     0.149780   10        1          0  0.068455        0  0.000037  0.000000
1     0.156388    7        1          1  0.108750        1  0.000043  0.000000
2     0.160793    4        2          2  0.062590        1  0.000041  0.000000
3     0.149780    4        1          2  0.064281        1  0.000042  0.061224
4     0.213656    1        1          1  0.044469        1  0.000043  0.000000
...        ...  ...      ...        ...       ...      ...       ...       ...
4516  0.301762    7        1          1  0.039999        1  0.000047  0.081633
4517  0.209251    6        1          2  0.000000        1  0.000027  0.000000
4518  0.209251    9        1          1  0.048429        0  0.000040  0.204082
4519  0.145374    1        1          1  0.059731        0  0.000039  0.061224
4520  0.180617    2        2          2  0.059717        1  0.000048  0.020408

[4521 rows x 8 columns]

In [17]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4516    0
4517    0
4518    0
4519    0
4520    0
Name: approval, Length: 4521, dtype: int64