#### Numpy

In [1]:
#!pip install numpy
#pip install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np  ##import is keyword, as is alias, np is alias
print(np.__version__)

2.3.0


In [3]:
lst=list(range(1,25))

In [4]:
type(lst)

list

In [5]:
#array and list

#array is homogenous
#list is heterogemous

#list conert into arrat

arr=np.array(lst)

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,5,6])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6])

In [13]:
arr=np.arange(1,25)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
arr=np.zeros((5,10))  ## 5 row 10 colum
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
arr=np.linspace(1,10,5)  ##random five no. between 1 to 10 
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
arr=np.arange(0,30)

In [22]:
arr.reshape(10,3) ##3 columns or 10 rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [24]:
arr=np.random.randint(1,5,9)
arr

array([3, 1, 3, 3, 2, 1, 1, 3, 3], dtype=int32)

In [25]:
arr=np.random.random(10)

In [26]:
arr

array([0.88815714, 0.12561496, 0.35312308, 0.62168787, 0.58511957,
       0.74640626, 0.61189914, 0.65497988, 0.68317089, 0.32035087])

In [27]:
np.random.random((5,10))

array([[0.46269553, 0.390817  , 0.68793464, 0.78952643, 0.97481411,
        0.05157879, 0.70096385, 0.55530845, 0.08379647, 0.73267038],
       [0.61488637, 0.40066628, 0.06125243, 0.57744755, 0.62996505,
        0.10951834, 0.69384573, 0.72463487, 0.48932095, 0.53789479],
       [0.66040059, 0.16496202, 0.43280516, 0.36729581, 0.88359622,
        0.09523284, 0.13096067, 0.04513167, 0.5036999 , 0.30873678],
       [0.66830319, 0.79508151, 0.73787096, 0.20074509, 0.01008294,
        0.71969298, 0.74308729, 0.17369865, 0.03832642, 0.33949672],
       [0.71167878, 0.0525987 , 0.14473984, 0.15853617, 0.01330092,
        0.29664921, 0.96142727, 0.75301501, 0.50213563, 0.81187429]])

### Array Attribute

In [28]:
arr=np.arange(60).reshape(12,5)  #12 row and 5 column
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [29]:
print("array shape:-",arr.shape)
print("array size:-",arr.size)
print("array datatype:-",arr.dtype)
print("array ndim:-",arr.ndim)


array shape:- (12, 5)
array size:- 60
array datatype:- int64
array ndim:- 2


In [30]:
#2d array convert into 1d

arr=arr.flatten()
print("array shape:-",arr.shape)
print("array size:-",arr.size)
print("array datatype:-",arr.dtype)
print("array ndim:-",arr.ndim)


array shape:- (60,)
array size:- 60
array datatype:- int64
array ndim:- 1


In [31]:
lst=[[1,2,3],[4,5,6]]

In [32]:
arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr.shape

(2, 3)

In [34]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Accessing element from array 1D and 2D array
for 1D array
[row start:row end:row step]

for 2D array
[row start:row end:row step]

In [39]:
arr=np.arange(60)


In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [42]:
arr[0:25:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [43]:
arr=arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [44]:
arr[1]

array([5, 6, 7, 8, 9])

In [45]:
arr[1,1]

np.int64(6)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [49]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [52]:
##last element
arr[11:12,4]

array([59])

In [53]:
arr[11,4:5]

array([59])

In [54]:
arr[11][-1]

np.int64(59)

In [55]:
arr[-1][-1]

np.int64(59)

In [56]:
arr[11,-1]

np.int64(59)

In [59]:
##3d array
arr=np.array(np.arange(225).reshape(5,15,3))

In [60]:
arr.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr.shape
#(5,15,3)
#5 tables
#15 rows
#3 columns

In [61]:
print("Dimension of arrat:-",arr.ndim)

Dimension of arrat:- 3


In [62]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [63]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [64]:
arr[:,0,:1]

array([[  0],
       [ 45],
       [ 90],
       [135],
       [180]])

In [65]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [66]:
arr[2][3][1]=500

In [67]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 500, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [68]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(arr+2)
print(arr*2)
print(arr1/arr2)
print(arr1*arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1**2)
print(arr1**3)
#arr.short



[ 3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  1   4   9  16  25  36  49  64  81 100]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]
